- CMakeLists.txt
- src/database/DBOperation.cpp
- src/database/DBOperation.h
- src/database/DBOperationQueue.cpp
- src/database/DBOperationQueue.h
- src/database/DatabaseServer.cpp
- src/database/DatabaseServer.h
This implements a more disciplined work queue into the database server that ensures that no two conflicting operations will be submitted to the backend at once. The current implementation will only allow one operation on a doId to run at a time (with the exception of GET_FIELDS/GET_OBJECT, which can run as much as it wants). In the future I'd like to figure out how to get the DBOperation::is_independent_of function working better so that it can properly detect when it can safely coexist with another operation.
> Resolve database race condition with multithreaded backends

- README.md
Fix a minor typo in the readme that made the link to the build instructions not work.
> Fix typo/broken link

- src/config/ConfigGroup.cpp
- src/config/ConfigGroup.h
- src/database/DatabaseBackend.cpp
- src/database/DatabaseBackend.h
- src/database/YAMLDatabase.cpp
This branch introduces a "KeyedConfigGroup" that can be used for ClientAgent/Client config and Database/Backend config so that each client type and backend type don't have conflicting config variable names.
@CFSworks to use in MongoDB finishing.
> KeyedConfigGroup

- src/clientagent/Client.cpp
Reported by @mfwass via IRC: http://pastebin.com/vkahz7BP
> ClientAgent: Remove unused variables to squelch compiler warnings

- src/clientagent/AstronClient.cpp
- src/clientagent/Client.cpp
- src/clientagent/Client.h
- src/messagedirector/MDNetworkParticipant.cpp
- src/messagedirector/MDNetworkParticipant.h
- src/messagedirector/MDNetworkUpstream.cpp
- src/messagedirector/MDNetworkUpstream.h
- src/net/NetworkClient.cpp
- src/net/NetworkClient.h
This PR changes `NetworkClient` so that you no longer subclass it. Instead, you subclass a new `NetworkHandler` type and pass it to the `NetworkClient` on creation; this is how callbacks are delivered.
Further, some stricter lifecycle changes have been made. It's an explicit error to allow the `NetworkClient` to destruct without disconnecting it first, and the appropriate way to use `NetworkClient` is always through a shared smart pointer, to ensure that the `NetworkClient` object stays valid until all callbacks finish.
There are also some small cleanups here and there - for example, `send_disconnect` is just `disconnect` now.
> Refactor NetworkClient

- src/clientagent/AstronClient.cpp
- src/clientagent/Client.cpp
- src/clientagent/Client.h
- src/util/Timeout.cpp
- src/util/Timeout.h
This involves converting Timeout to an object counted with shared pointers
(so that the ASIO callback can function correctly even after the Timeout
object itself is dereferenced by its parent object) and requiring an
explicit cancel.
In particular, InterestOperation explicitly cancels and only bothers
cleaning up manually if the cancelation fails.
> Fix race condition when Timeout is canceled from a separate thread.

- src/clientagent/ClientAgent.cpp
- src/net/SslAcceptor.cpp
- src/net/SslAcceptor.h
- test/test_clientagent.py
This adds a 5000ms timeout for newly-connecting clients to issue an SSL handshake before the server closes the connection.
Without this, clients may sometimes connect and, before performing the handshake, silently lose their connection (i.e. no TCP RST/FIN, due to e.g. power loss). With no traffic, the TCP connection will never time out from a missing ACK, and with the server waiting indefinitely for an SSL handshake, no traffic is ever sent.
Comments welcome as to whether 5000ms is a good number, whether it should be configurable, higher, lower, etc.
> SSL handshake timeout

- .travis.yml
- README.md
- src/util/Timeout.h
- test/test_config.py
This seems to be the hip trend on GitHub: add a `.travis.yml` and toggle on Travis-CI integration.
This PR mostly creates such a file, but also disables the IPv6 binding tests when the host has no IPv6 loopback (as seems to be the case with Travis's job runners).
MongoDB test support to come in a future PR.
> Use Travis CI

- CMakeLists.txt
- docs/config/astron.example.yml
- src/clientagent/AstronClient.cpp
- src/clientagent/ClientAgent.cpp
- src/clientagent/ClientAgent.h
- src/clientagent/ClientFactory.cpp
- src/clientagent/ClientFactory.h
- src/messagedirector/MDNetworkParticipant.cpp
- src/messagedirector/MDNetworkUpstream.cpp
- src/net/HAProxyHandler.cpp
- src/net/HAProxyHandler.h
- src/net/NetworkAcceptor.h
- src/net/NetworkClient.cpp
- src/net/NetworkClient.h
- src/net/SslAcceptor.cpp
- src/net/SslAcceptor.h
- src/net/TcpAcceptor.cpp
- src/net/TcpAcceptor.h
- test/test_clientagent.py
This adds an extra flag to the ClientAgent role titled `haproxy` that, when set to `true`, configures the CA to expect a [PROXY protocol header](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt) at the beginning of the connection.
This allows the connection endpoint information (a la `CLIENTAGENT_GET_NETWORK_ADDRESS`) to persist across a layer-4 proxy that speaks the PROXY protocol (v1/v2). The added benefit here is that the proxy can even do the SSL termination.
Some software which could be used to do this:
- AWS Elastic Load Balancers
- HAProxy
- Stunnel
> Support HAProxy PROXY protocol

- src/clientagent/AstronClient.cpp
- src/clientagent/ClientAgent.cpp
- src/clientagent/ClientAgent.h
- src/config/ConfigGroup.cpp
- src/config/ConfigGroup.h
**NOTE**: This DOES change client configuration to a KeyedConfigGroup. If you have a fork with a custom client type, please update your configuration appropriately.
This PR mainly changes `ConfigGroup` not to rely on its parent group in the constructor, because thanks to undefined static-initialization ordering, it might not be ready yet.
> Fix static-initialization ordering problems in config subsystem

- test/common/astron.py
- test/common/dbserver.py
- test/common/dcfile.py
- test/files/test.dc
The various DB server(s) often convert Bamboo/Astron types to and from their backends' datatypes. As such, it's necessary to have tests to verify that this conversion works correctly.
> Add DB tests for various datatypes

- src/clientagent/Client.cpp
- test/test_clientagent.py
There's a bug with interests. If an object moves from `(old_parent, old_zone)` to `(new_parent, new_zone)`, it won't get disabled if we have an interest in `(any_parent, new_zone)`, even though we don't have any interest in `(new_parent, new_zone)`.
> Fix interest bug with parents

- src/clientagent/AstronClient.cpp
- src/clientagent/Client.cpp
- src/clientagent/Client.h
- test/test_clientagent.py
In a nutshell, a client can have two views of an object: a DistributedObject instance and a DistributedObjectOV
The owner view instance (DistObjectOV) is created when the client receives _CLIENT\_ENTER\_OBJECT\_REQUIRED[\_OTHER]\_OWNER_ (i.e. as soon as _STATESERVER\_OBJECT\_SET\_OWNER_ is dispatched).
The "regular" view, on the other hand, only exists while the client has interest in the object's location.
For example, a game may give to the client the ownership of a DistributedShip object upon the avatar's login. That causes DistributedShipOV to generate. With that view, the client can hear some important updates: setMasts, setArmor and even send ownsend updates.
When the ship is deployed, the server moves it to a certain location so that the client may find it with an interest and …
> Change how ownerviews behave to resemble OTP

- src/clientagent/Client.cpp
Even though this works, it isn't a good idea to assume that Datagrams and strings will always have the same tag size. This was causing issues on a private fork where Datagram tags are 32-bit but strings are 16-bit.
> Client: Use read_datagram instead of read_string

- CMakeLists.txt
This should eliminate weird linker errors, plus you can always override
it if you want. We technically already do this in Travis, so may as well
make it a default behavior and save some headaches.
Fixes #385
> cmake: Link to Homebrew OpenSSL on MacOS by default

- src/messagedirector/MessageDirector.cpp
If a truncated datagram is detected in handle_datagram from an unknown participant, Astron crashes when trying to log the name of the participant. This commit handles logging if the participant is unknown in this case.
> messagedirector: Fix core crash caused by logging unknown participant

- docs/building/build-readme.md
- Include libuv dependency + source location
- Replace broken libyaml link with updated source location
- Remove reference to boost:asio in note about old boost versions, since it's been replaced in Astron with libuv
> readme: Include libuv dependency; remove broken libyaml link

- src/core/Logger.cpp
Since the switch statement that initialized `severity_label` had no default case, the compiler flags this as a warning and stops compilation due to it being possibly uninitialized :)
> core: Default case to ensure `severity_label` is initialized

- src/core/shutdown.cpp
If you interrupt the program (Ctrl + C), it will say "Exiting ..." and keep running with the exit mutex locked but no exit call.
This adds that missing exit call for manual interrupts that don't have an exception to throw when shutdown is called.
> core: Exit after astron_shutdown() is called without an exception

- .gitignore
- docs/building/linux-gnu-make.md
Not sure why the build instructions for GNU Make/Linux say to specifically exclude these build artifacts from git via manually writing to the `.git/info/exclude` file instead of having these artifacts listed in the project gitignore instead.
The removed portion of the build instructions said this:
```
Because build artifacts vary wildly between all the operating systems
and compilers that Astron will compile with, they are not included in the .gitignore file.
```
We can include any artifacts (from any operating system Astron may be compiled in) in this file.
> gitignore: Ignore GNU Make/Linux build artifacts
